namespace PiCompanion.Core.Events;

public enum CompanionRunEventKind
{
    RunQueued,
    RunStarted,
    RunSettled,
    RunFailed,
    RunInterrupted,
    UserMessageAdded,
    AssistantMessageStarted,
    AssistantTextDelta,
    AssistantThinkingDelta,
    AssistantMessageCompleted,
    ToolStarted,
    ToolProgressed,
    ToolCompleted,
    ToolFailed,
    ApprovalRequested,
    QuestionRequested,
    InteractionResolved,
    QueueChanged,
    CompactionStarted,
    CompactionCompleted,
    AutoRetryStarted,
    AutoRetryCompleted,
    SummarizationRetryStarted,
    SummarizationRetryProgressed,
    SummarizationRetryCompleted,
    SessionSynchronized,
    ModelChanged,
    ThinkingLevelChanged,
    FileChangeDetected,
    TestExecutionDetected,
    WarningRaised,
    RecoveryAvailable,
}
